---
neo4j_version: "5"
neo4j_admin_user: neo4j
# This references the secret stored in group_vars/all/vault.yml
neo4j_admin_password: "{{ vault_neo4j_admin_password }}"

neo4j_http_port: 7474
neo4j_bolt_port: 7687