---
# User and Group
api_user: hornet
api_group: hornet

# Paths
api_base_dir: /opt/hornet-api
api_app_dir: /opt/hornet-api/app
api_venv_dir: /opt/hornet-api/venv

# Network
api_host: 0.0.0.0
api_port: 8000

# env files 
postgres_dsn: "postgresql+psycopg2://postgres:password@localhost:5432/postgres"
neo4j_uri: "bolt://localhost:7687"
neo4j_user: "neo4j"
neo4j_password: "12345678"