---
# User and Group
api_user: hornet
api_group: hornet

# Paths
api_base_dir: /opt/hornet-api
api_app_dir: /opt/hornet-api/app
api_venv_dir: /opt/hornet-api/venv

# Network
api_host: 127.0.0.1
api_port: 8000

# env files  - i changed this when vault created
# Database Connections (Referencing Vault)
postgres_dsn: "{{ vault_postgres_dsn }}"
neo4j_uri: "bolt://localhost:7687"
neo4j_user: "neo4j"
neo4j_password: "{{ vault_neo4j_app_password }}"