---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Remove default Nginx config
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Deploy API reverse proxy config
  ansible.builtin.template:
    src: api_proxy.conf.j2
    dest: /etc/nginx/sites-available/hornet_api.conf
    mode: '0644'
  notify: Restart nginx

- name: Enable API reverse proxy config
  ansible.builtin.file:
    src: /etc/nginx/sites-available/hornet_api.conf
    dest: /etc/nginx/sites-enabled/hornet_api.conf
    state: link
  notify: Restart nginx

- name: Ensure Nginx is started and enabled
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes